# -*- coding: utf-8 -*-
"""multimodalemotion (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lduInYbuHGua7ZSX-Tq-TP4WvlQLc_13
"""

import tensorflow as tf
import librosa
import librosa.display
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import os
import torchaudio
import torch.nn.functional as F
import kagglehub
from transformers import AutoTokenizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, Dense, Dropout, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import MaxPooling1D
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Dropout, Bidirectional

# Preprocessing for CNN

path = kagglehub.dataset_download("uwrfkaggler/ravdess-emotional-speech-audio")

wav = []
for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith(".wav"):
            wav.append(os.path.join(root, file))

path = wav[0]


audio, sr = librosa.load(path, sr=16000) # using 16k because its the standard for nlp
print(f"Sample rate after Resampling: {sr}")

target_length = 3 * 16000
if len(audio) > target_length:
    # truncate
    audio = audio[:target_length]
else:
    # pad with zeros
    audio = F.pad(audio, (0, target_length - len(audio)))

def logmel_spectrogram(y, sr, n_mels=128, hop_length=512):
    mel_spectrogram = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels, hop_length=hop_length)
    logmel_spectrogram = librosa.power_to_db(mel_spectrogram, ref=np.max)
    return logmel_spectrogram

logmel_spectrogram = logmel_spectrogram(audio, sr=16000)

plt.figure(figsize=(8, 4))
librosa.display.specshow(logmel_spectrogram, sr=sr, hop_length=512, x_axis='time', y_axis='mel')
plt.colorbar(format='%+2.0f dB')
plt.title('Log-Mel Spectrogram')
plt.show()

print(wav)

!pip install openai-whisper
import whisper

'''
model = whisper.load_model("base")

transcriptions = []
for audio_path in wav[:500]: # started with 10 to test
    result = model.transcribe(audio_path)
    transcriptions.append({
        "file": os.path.basename(audio_path),
        "text": result["text"].strip()
    })

with open("transcript.txt", "w", encoding="utf-8") as f:
    for item in transcriptions:
        f.write(f"{item['file']}: {item['text']}\n")
'''

'''
!pip install transformers

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
with open("transcript.txt", "r", encoding="utf-8") as f:
    lines = f.readlines()

texts = [line.split(":", 1)[1].strip() for line in lines if ":" in line]
tokenized = tokenizer(
    texts,
    padding='max_length', # pad to longest in batch
    truncation=True, # truncate if over max_length
    max_length=128,
    return_tensors="pt"  # return PyTorch tensors
)
'''

#HARDCODE
def get_transcript(filepath):
    filename = os.path.basename(filepath)
    statement = filename.split("-")[5]   # 5th field

    if statement == "01":
        return "kids are talking by the door"
    else:
        return "dogs are sitting by the door"

transcripts = [get_transcript(f) for f in wav]

#mapping emotions and loading using librosa

emotions=[]

#Emotion (01 = neutral, 02 = calm, 03 = happy, 04 = sad, 05 = angry, 06 = fear, 07 = disgust, 08 = surprised)
for file in wav:
    if file.split('-')[5] == '01':
        emotions.append("neutral")
    elif file.split('-')[5] == '02':
        emotions.append("calm")
    elif file.split('-')[5] == '03':
        emotions.append("happy")
    elif file.split('-')[5] == '04':
        emotions.append("sad")
    elif file.split('-')[5] == '05':
        emotions.append("angry")
    elif file.split('-')[5] == '06':
        emotions.append("fear")
    elif file.split('-')[5] == '07':
        emotions.append("disgust")
    elif file.split('-')[5] == '08':
        emotions.append("surprised")

print(emotions)

rawdata = pd.DataFrame(columns=['feature'])
check = 0

for file in wav:
    x, sr = librosa.load(file,duration=3,sr=16000,offset=0.5)

    # Extract MFCCs
    mfccs = librosa.feature.mfcc(y=x, sr=sr, n_mfcc=40)
    mfccs_mean = np.mean(mfccs, axis=1)
    rawdata.loc[check] = [mfccs_mean]
    check += 1

print(f"Feature shape: {mfccs_mean.shape}")
print(rawdata.head())

#adding emotions column
rawdata['emotions'] = emotions
print(rawdata.head())

lb = LabelEncoder()
y_encoded = lb.fit_transform(emotions)  # angry→0, calm→1 etc.

X = np.array(rawdata['feature'].tolist())

df = pd.DataFrame(X)
df['label'] = y_encoded
df['transcript'] = transcripts

print(np.unique(y_encoded, return_counts=True))
print(lb.classes_) #neutral has way too many samples --> need to undersample so that every emotion has 192

neutral_label = list(lb.classes_).index('neutral')
neutral_down = df[df['label'] == neutral_label].sample(n=192, random_state=42)
others = df[df['label'] != neutral_label]
df_balanced = pd.concat([neutral_down, others]).sample(frac=1, random_state=42)
y_encoded = df_balanced['label'].values
X = df_balanced.drop(['label', 'transcript'], axis=1).values
transcripts_bal = df_balanced['transcript'].tolist()  # balancing transcript text as well

print(np.unique(y_encoded, return_counts=True))

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

# labelmap
y_lb_encoded = dict(enumerate(lb.classes_))

# checking shapes of data
#print(f'X_train shape: {X_train.shape}')
#print(f'y_train shape: {y_train.shape}')
#print(f'X_test shape: {X_test.shape}')
#print(f'y_test shape: {y_test.shape}')

# Normalizing the data
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

x_traincnn = np.expand_dims(X_train_scaled, axis=2)
x_testcnn = np.expand_dims(X_test_scaled, axis=2)

CNN_model = Sequential([
    Conv1D(64,  3, padding='same', activation='relu', input_shape=(40, 1)),
    Conv1D(128, 3, padding='same', activation='relu'),
    #MaxPooling1D(2),
    Conv1D(128, 3, padding='same', activation='relu'),
    Conv1D(256, 3, padding='same', activation='relu'),
    Dropout(0.3),
    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(8, activation='softmax')
])

'''
previous model - tried bigger kernel before
CNN_model = Sequential([
    Conv1D(16, 5, padding='same', activation='relu', input_shape=(40, 1)),
    Conv1D(32, 5, padding='same', activation='relu'),
    Conv1D(64, 5, padding='same', activation='relu'),
    Conv1D(128, 5, padding='same', activation='relu'),
    Dropout(0.4),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(64, activation='relu'),
    Dense(8, activation='softmax')
])

'''

CNN_model.compile(
    optimizer=Adam(learning_rate=0.0001),  # lowering lr
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

CNN_model.summary()

# Train
results = CNN_model.fit(x_traincnn, y_train,
    epochs=25,
    batch_size=32,
    verbose =1,
    validation_data=(x_testcnn, y_test)
 )

# Evaluate
loss, accuracy = CNN_model.evaluate(x_testcnn, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

# Visualising predictions versus actual labels

y_pred = np.argmax(CNN_model.predict(x_testcnn), axis=1)
print(classification_report(y_test, y_pred, target_names=lb.classes_))

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(results.history['loss'], label='Train Loss')
plt.plot(results.history['val_loss'], label='Test Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(results.history['accuracy'], label='Train Accuracy')
plt.plot(results.history['val_accuracy'], label='Test Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

# confusion matrix heatmap - looking for diagonal dominance
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=lb.classes_,
            yticklabels=lb.classes_)
plt.title('Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

# Preprocessing for RNN

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

tokenized = tokenizer(
    transcripts_bal,
    padding='max_length',
    truncation=True,
    max_length=128,
    return_tensors="pt"
)

X_text = tokenized['input_ids'].numpy()

vocab_size = tokenizer.vocab_size
embed_dim = 128
hidden_dim = 256
num_classes = 8 # there are 8 emotions so we can write this directly
max_length = 128

# Embedding layer + LSTM
inputs  = Input(shape=(max_length,))
x = Embedding(input_dim=vocab_size, output_dim=embed_dim, mask_zero=True)(inputs)
x = Bidirectional(LSTM(hidden_dim, dropout=0.4))(x)
x = Dense(64, activation='relu')(x)
x = Dropout(0.4)(x)
outputs = Dense(num_classes, activation='softmax')(x)

text_model = Model(inputs, outputs)
text_model.summary()

X_text = tokenized['input_ids'].numpy()
y_text = y_encoded

X_train_text, X_test_text, y_train_text, y_test_text = train_test_split(X_text, y_text, test_size=0.2, random_state=42)

# Train

text_model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

text_history = text_model.fit(
    X_train_text, y_train_text,
    epochs=25,
    batch_size=32,
    verbose = 1,
    validation_data=(X_test_text, y_test_text)
)

# Visualising

y_pred = np.argmax(text_model.predict(X_test_text), axis=1)
print(classification_report(y_test_text, y_pred, target_names=lb.classes_))

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(text_history.history['loss'], label='Train Loss')
plt.plot(text_history.history['val_loss'], label='Test Loss')
plt.title('Text Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(text_history.history['accuracy'], label='Train Accuracy')
plt.plot(text_history.history['val_accuracy'], label='Test Accuracy')
plt.title('Text Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

cm_text = confusion_matrix(y_test_text, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm_text, annot=True, fmt='d', cmap='Greens',
            xticklabels=lb.classes_,
            yticklabels=lb.classes_)
plt.title('Text Model Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

#multimodal fusion


audio_probs = CNN_model.predict(x_testcnn)
text_probs = text_model.predict(X_test_text)

# Using weighted avg formula
y_pred_fused = np.argmax(0.7*audio_probs + 0.3*text_probs, axis=1)

print(f"Accuracy:  {accuracy_score(y_test, y_pred_fused)*100:.4f}%")
print(classification_report(y_test, y_pred_fused, target_names=lb.classes_))


cm = confusion_matrix(y_test, y_pred_fused)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Purples',
            xticklabels=lb.classes_,
            yticklabels=lb.classes_)
plt.title('Multimodal Fusion Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

# comparing all three models
audio_pred = np.argmax(audio_probs, axis=1)
text_pred = np.argmax(text_probs, axis=1)

print("Model Comparison:")
print(f"Audio CNN only: {accuracy_score(y_test, audio_pred)*100:.4f}%")
print(f"Text LSTM only: {accuracy_score(y_test, text_pred)*100:.4f}%")
print(f"Multimodal fusion: {accuracy_score(y_test, y_pred_fused)*100:.4f}%")